include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "test_raw_upload.dart"
    - "test_storage.dart"
    - "test_storage_2.dart"

linter:
  rules:
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - avoid_print
    - prefer_const_constructors
    - prefer_const_declarations
